version: '3.8'

services:
  postgresdb:
    image: 'postgres:15-alpine'
    container_name: postgresdb_container_name
    restart: always
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: springboot_app_container
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/db_name
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres_data: